"""empty message

Revision ID: b445f98ef2a6
Revises: 795bab50e83f
Create Date: 2020-08-01 21:54:48.007033

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b445f98ef2a6'
down_revision = '795bab50e83f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('product', 'description',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('product', 'last_update',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('user', 'last_update',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'last_update',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('product', 'last_update',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('product', 'description',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###
